import {
  Bell,
  CircleCheckFilled,
  Close,
  DataAnalysis,
  Delete,
  DocumentChecked,
  Download,
  EditPen,
  Expand,
  Filter,
  Finished,
  Fold,
  Grid,
  Loading,
  Menu,
  MoreFilled,
  Refresh,
  Search,
  Setting,
  Upload,
  User,
  View,
  WarningFilled,
} from '@element-plus/icons-vue'

export const AppIcons = {
  navigation: {
    dashboard: DataAnalysis,
    projects: DocumentChecked,
    tasks: Finished,
    rules: Setting,
    foundation: Grid,
  },
  action: {
    search: Search,
    filter: Filter,
    refresh: Refresh,
    upload: Upload,
    download: Download,
    view: View,
    edit: EditPen,
    delete: Delete,
    more: MoreFilled,
  },
  layout: {
    menu: Menu,
    collapse: Fold,
    expand: Expand,
    close: Close,
  },
  status: {
    success: CircleCheckFilled,
    warning: WarningFilled,
    loading: Loading,
  },
  account: {
    user: User,
    notification: Bell,
  },
} as const
