/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./components/common/AppLogo.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    AppTopbar: typeof import('./components/layout/AppTopbar.vue')['default']
    BaseCard: typeof import('./components/common/BaseCard.vue')['default']
    BaseTableCard: typeof import('./components/common/BaseTableCard.vue')['default']
    ConfirmActionDialog: typeof import('./components/common/ConfirmActionDialog.vue')['default']
    DescriptionList: typeof import('./components/common/DescriptionList.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    ErrorState: typeof import('./components/common/ErrorState.vue')['default']
    FilterBar: typeof import('./components/common/FilterBar.vue')['default']
    GlobalErrorNotice: typeof import('./components/common/GlobalErrorNotice.vue')['default']
    IconButton: typeof import('./components/common/IconButton.vue')['default']
    InlineNotice: typeof import('./components/common/InlineNotice.vue')['default']
    LoadingState: typeof import('./components/common/LoadingState.vue')['default']
    MetricCard: typeof import('./components/common/MetricCard.vue')['default']
    PageHeader: typeof import('./components/common/PageHeader.vue')['default']
    PaginationBar: typeof import('./components/common/PaginationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./components/common/SectionHeader.vue')['default']
    StatusTag: typeof import('./components/common/StatusTag.vue')['default']
  }
}
